=== l1analytics/onelend-backend/shemas/valuation/order.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Order Schema",
    "type": "object",
    "properties": {
      "referenceNumber": {
        "type": "string"
      },
      "complexProperty": {
        "type": "boolean"
      },
      "priority": {
        "type": "boolean"
      },
      "requestedDueDate": {
        "type": "string"
      },
      "fhaCaseNumber": {
        "type": "string"
      },
      "internalComment": {
        "type": "string"
      },
      "duCaseFileID": {
        "type": "string"
      },
      "lpaKey": {
        "type": "string"
      },
      "vendorInstructions": {
        "type": "string"
      },
      "requestingParty": {
        "type": "object",
        "properties": {
          "clientID": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "contactName": {
            "type": "string"
          }
        },
        "required": [
          "clientID",
          "name",
          "contactName"
        ]
      },
      "request": {
        "type": "object",
        "properties": {
          "internalAccountID": {
            "type": "string"
          },
          "branchID": {
            "type": "string"
          },
          "loanAmount": {
            "type": "number"
          },
          "salesPrice": {
            "type": "number"
          },
          "estimatedValue": {
            "type": "number"
          },
          "loanType": {
            "type": "string"
          },
          "transactionUID": {
            "type": "string"
          },
          "requestData": {
            "type": "object",
            "properties": {
              "action": {
                "type": "string"
              },
              "loan": {
                "type": "object",
                "properties": {
                  "application": {
                    "type": "object",
                    "properties": {
                      "property": {
                        "type": "object",
                        "properties": {
                          "streetAddress": {
                            "type": "string"
                          },
                          "city": {
                            "type": "string"
                          },
                          "state": {
                            "type": "string"
                          },
                          "county": {
                            "type": "string"
                          },
                          "zip": {
                            "type": "string"
                          },
                          "propertyType": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "streetAddress",
                          "city",
                          "state",
                          "county",
                          "zip",
                          "propertyType"
                        ]
                      }
                    },
                    "required": [
                      "property"
                    ]
                  },
                  "product": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "code": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "name",
                      "code"
                    ]
                  },
                  "embeddedFile": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "typeID": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "description": {
                          "type": "string"
                        },
                        "document": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "typeID",
                        "name",
                        "description",
                        "document"
                      ]
                    }
                  },
                  "parties": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "partyType": {
                          "type": "string"
                        },
                        "firstName": {
                          "type": "string"
                        },
                        "middleName": {
                          "type": "string"
                        },
                        "lastName": {
                          "type": "string"
                        },
                        "fullName": {
                          "type": "string"
                        },
                        "contactMethod": {
                          "type": "object",
                          "properties": {
                            "contactInfo": {
                              "type": "array",
                              "items": {
                                "type": "object",
                                "properties": {
                                  "contactLabel": {
                                    "type": "string"
                                  },
                                  "contactType": {
                                    "type": "string"
                                  },
                                  "contactValue": {
                                    "type": "string"
                                  }
                                },
                                "required": [
                                  "contactLabel",
                                  "contactType",
                                  "contactValue"
                                ]
                              }
                            }
                          },
                          "required": [
                            "contactInfo"
                          ]
                        }
                      },
                      "required": [
                        "partyType",
                        "firstName",
                        "middleName",
                        "lastName",
                        "fullName",
                        "contactMethod"
                      ]
                    }
                  }
                },
                "required": [
                  "application",
                  "product",
                  "embeddedFile",
                  "parties"
                ]
              }
            },
            "required": [
              "action",
              "loan"
            ]
          }
        },
        "required": [
          "internalAccountID",
          "branchID",
          "loanAmount",
          "salesPrice",
          "estimatedValue",
          "loanType",
          "transactionUID",
          "requestData"
        ]
      }
    },
    "required": [
      "referenceNumber",
      "complexProperty",
      "priority",
      "requestedDueDate",
      "fhaCaseNumber",
      "internalComment",
      "duCaseFileID",
      "lpaKey",
      "vendorInstructions",
      "requestingParty",
      "request"
    ]
  }

=== l1analytics/onelend-backend/shemas/valuation/order-example.json
{
    "referenceNumber": "demoAPI-012345",
    "complexProperty": false,
    "priority": false,
    "requestedDueDate": "12/22/2023",
    "fhaCaseNumber": "456-1569785",
    "internalComment": "Comments for the appraisal desk and review team.",
    "duCaseFileID": "02-34567890",
    "lpaKey": "01-23456789",
    "vendorInstructions": "Comments for the appraiser or AMC.",
    "requestingParty": {
        "clientID": "4564",
        "name": "ABC Lender",
        "contactName": "John Smith"
    },
    "request": {
        "internalAccountID": "12345",
        "branchID": "Branch4567",
        "loanAmount": 300000.00,
        "salesPrice": 350000.00,
        "estimatedValue": 350000.00,
        "loanType": "Purchase",
        "transactionUID": "81B9-F16E-03D8-4C3F",
        "requestData": {
       	    "action": "Original",
            "loan": {
               "application": {
                   "property": {
                      "streetAddress": "6000 Freedom Square Dr.",
                      "city": "Independence",
                      "state": "OH",
                      "county": "Cuyahoga",
                      "zip": "44131",
                      "propertyType": "Single Family"
                   }
               },
               "product": {
                  "name": "FNMA 1004 Single Family",
                  "code": "A001"
               },
               "embeddedFile": [
               {
       	          "typeID": "1010",
                  "name": "purchasecontract.PDF",
      	          "description": "Purchase Contract",
      	          "document": "Base64 encoded document"
               }
               ],
               "parties": [
               {
                  "partyType": "Borrower",
                  "firstName": "Connie",
                  "middleName": "H",
                  "lastName": "Borrower",
                  "fullName": "Connie H Borrower",
                  "contactMethod": {
                     "contactInfo": [
                     {
                        "contactLabel": "Home",
                        "contactType": "Phone",
                        "contactValue": "(440) 222-3333"
                     },
                     {
                        "contactLabel": "Home",
                        "contactType": "Email",
                        "contactValue": "connie@donotusetest.com"
                     }
                     ]
                  }
               },   
               {
                  "partyType": "Appraisal Coordinator",
                  "firstName": "Angie",
                  "middleName": "T",
                  "lastName": "Manager",
                  "fullName": "Angie T Manager",
                  "contactMethod": {
                     "contactInfo": [
                     {
                        "contactLabel": "Mobile",
                        "contactType": "Phone",
                        "contactValue": "(919) 933-7717"
                     },
                     {
                        "contactLabel": "Home",
                        "contactType": "Email",
                        "contactValue": "angie@donotusetest.com"
                     }
                     ]
                  }
               },
               {
                  "partyType": "Property Contact",
                  "firstName": "Peter",
                  "middleName": "T",
                  "lastName": "contact",
                  "fullName": "Peter T Contact",
                  "contactMethod": {
                     "contactInfo": [
                     {
                        "contactLabel": "Home",
                        "contactType": "Phone",
                        "contactValue": "(919) 933-2517"
                     },
                     {
                        "contactLabel": "Work",
                        "contactType": "Email",
                        "contactValue": "peter@donotusetest.com"
                     }
                     ]
                  }
               },
               {
                  "partyType": "Loan Officer",
                  "firstName": "Debbie",
                  "middleName": "",
                  "lastName": "Officer",
                  "fullName": "Debbie Officer",
                  "contactMethod": {
                     "contactInfo": [
                     {
                        "contactLabel": "Work",
                        "contactType": "Phone",
                        "contactValue": "(984) 219-5641"
                     },
                     {
                        "contactLabel": "Work",
                        "contactType": "Email",
                        "contactValue": "Debbie@donotusetest.com"
                     }
                     ]
                  }
               },
               {
                  "partyType": "Loan Processor",
                  "firstName": "Martin",
                  "middleName": "J",
                  "lastName": "Processor",
                  "fullName": "Martin J Processor",
                  "contactMethod": {
                     "contactInfo": [
                     {
                        "contactLabel": "Work",
                        "contactType": "Phone",
                        "contactValue": "(222) 333-5555"
                     },
                     {
                        "contactLabel": "Work",
                        "contactType": "Email",
                        "contactValue": "Martin@donotuse.test.com"
                     }
                     ]
                  }
               }
               ] 
            }  
        }
    }
}
